
["Mod Compatibility Options"]
	#
	# Attempt to add modded features from vanilla biomes into Ultra Amplified version of that biome.
	# Only works if other mod added the feature by addFeature(...) to vanilla biome and registered the feature correctly without the 'minecraft' namespace.
	importModdedFeatures = false
	#
	# Attempt to add all registered modded biomes into Ultra Amplified dimension or worldtype.
	# You may want to turn up biome size to 4 or 5 as this may make biomes very crowded. Also overrides importModdedBiomes setting.
	importAllModdedBiomes = false
	#
	# Blacklist either all of a mod's structures or specific structures from being imported into Ultra Amplified dimension/worldtype.
	# To blacklist all structures in a mod, type out its id like so with :* attached at end. Example: "example_mod_id:*"
	# To blacklist a specific mod's structure, type out the resourcelocation. Example: "example_mod_id:wizard_tower"
	# NOTE: Seperate each entry with a comma. Example: "example_mod_id_1:wizard_tower, example_mod_id_2:*, example_mod_id_1:super_village"
	# Also, any entry using ultra_amplified_dimension or minecraft id will be ignored as I already handle those ids internally.
	blacklistedFeatureList = ""
	#
	# Attempt to add modded mobs from vanilla biomes into Ultra Amplified version of that biome.
	# Only works if other mod added the mob by addSpawn(...) to vanilla biome and registered the mob correctly without the 'minecraft' namespace.
	importModdedMobs = false
	#
	# Blacklist either all of a mod's biomes or its specific biomes from being imported into Ultra Amplified dimension/worldtype.
	# To blacklist all of a mod's biomes, type out its id like so with :* attached at end. Example: "example_mod_id:*"
	# To blacklist a specific mod's biome, type out the resourcelocation. Example: "example_mod_id:lava_desert"
	# NOTE: Seperate each entry with a comma. Example: "example_mod_id_1:lava_desert, example_mod_id_2:*, example_mod_id_1:ender_forest"
	# Also, any entry using ultra_amplified_dimension or minecraft id will be ignored as I already handle those ids internally.
	blacklistedBiomeList = ""
	#
	# Attempt to add modded structures from vanilla biomes into Ultra Amplified version of that biome.
	# Only works if other mod added the structure by addFeature(...) to vanilla biome and registered the structure correctly without the 'minecraft' namespace.
	importModdedStructure = false
	#
	# Attempt to add modded biomes from Overworld into Ultra Amplified dimension. (or into Overworld in Ultra Amplified worldtype)
	# Only works if other mod added the biome to the BiomeDictionary with the BiomeType of DESERT, WARM, COOL, or ICY type.
	importModdedBiomes = false

